# Generated by Django 5.1.2 on 2025-01-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_customercompany_company_type_and_more"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customercompany",
            name="backend_skills",
            field=models.ManyToManyField(
                blank=True, related_name="customer_companies", to="skills.backendskill"
            ),
        ),
        migrations.AddField(
            model_name="customercompany",
            name="frontend_skills",
            field=models.ManyToManyField(
                blank=True, related_name="customer_companies", to="skills.frontendskill"
            ),
        ),
        migrations.AddField(
            model_name="customercompany",
            name="mobile_skills",
            field=models.ManyToManyField(
                blank=True, related_name="customer_companies", to="skills.mobileskill"
            ),
        ),
        migrations.AddField(
            model_name="employercompany",
            name="backend_skills",
            field=models.ManyToManyField(
                blank=True, related_name="employer_companies", to="skills.backendskill"
            ),
        ),
        migrations.AddField(
            model_name="employercompany",
            name="frontend_skills",
            field=models.ManyToManyField(
                blank=True, related_name="employer_companies", to="skills.frontendskill"
            ),
        ),
        migrations.AddField(
            model_name="employercompany",
            name="mobile_skills",
            field=models.ManyToManyField(
                blank=True, related_name="employer_companies", to="skills.mobileskill"
            ),
        ),
    ]
