# Generated by Django 5.1.2 on 2025-01-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_customercompany_backend_skills_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customercompany",
            name="backend_skills",
        ),
        migrations.RemoveField(
            model_name="customercompany",
            name="frontend_skills",
        ),
        migrations.RemoveField(
            model_name="customercompany",
            name="mobile_skills",
        ),
        migrations.RemoveField(
            model_name="employercompany",
            name="backend_skills",
        ),
        migrations.RemoveField(
            model_name="employercompany",
            name="frontend_skills",
        ),
        migrations.RemoveField(
            model_name="employercompany",
            name="mobile_skills",
        ),
    ]
