# Generated by Django 5.1.2 on 2025-01-04 14:46

import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackendSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("interested in learning", "Interested In Learning"),
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                            ("master", "Master"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "started_on",
                    models.DateField(
                        blank=True,
                        help_text="Date when this skill was started to be used or learned.",
                        null=True,
                    ),
                ),
                (
                    "last_used_on",
                    models.DateField(
                        blank=True, help_text="Date when this skill was last used.", null=True
                    ),
                ),
                (
                    "learned_with",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("courses", "Courses"),
                            ("practice", "Practice"),
                            ("exercises", "Exercises"),
                            ("projects", "Projects"),
                            ("books", "Books"),
                            ("tutorials", "Tutorials"),
                            ("documentations", "Documentations"),
                            ("mentors", "Mentors"),
                            ("ai bots", "Ai Bots"),
                            ("other", "Other"),
                        ],
                        help_text="Indicate with which tools or methods you learned this skill.",
                        max_length=88,
                        null=True,
                    ),
                ),
                (
                    "skill_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("language", "Language"),
                            ("framework", "Framework"),
                            ("library", "Library"),
                            ("tool", "Tool"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tool_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ide", "Ide"),
                            ("editor", "Editor"),
                            ("CI/CD", "Ci Cd"),
                            ("containerization", "Containerization"),
                            ("monitoring", "Monitoring"),
                            ("logging", "Logging"),
                            ("testing", "Testing"),
                            ("debugging", "Debugging"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("database", "Data Base"),
                            ("devops", "Devops"),
                            ("server", "Server"),
                            ("cloud", "Cloud"),
                            ("security", "Security"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FrontendSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("interested in learning", "Interested In Learning"),
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                            ("master", "Master"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "started_on",
                    models.DateField(
                        blank=True,
                        help_text="Date when this skill was started to be used or learned.",
                        null=True,
                    ),
                ),
                (
                    "last_used_on",
                    models.DateField(
                        blank=True, help_text="Date when this skill was last used.", null=True
                    ),
                ),
                (
                    "learned_with",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("courses", "Courses"),
                            ("practice", "Practice"),
                            ("exercises", "Exercises"),
                            ("projects", "Projects"),
                            ("books", "Books"),
                            ("tutorials", "Tutorials"),
                            ("documentations", "Documentations"),
                            ("mentors", "Mentors"),
                            ("ai bots", "Ai Bots"),
                            ("other", "Other"),
                        ],
                        help_text="Indicate with which tools or methods you learned this skill.",
                        max_length=88,
                        null=True,
                    ),
                ),
                (
                    "skill_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("language", "Language"),
                            ("framework", "Framework"),
                            ("library", "Library"),
                            ("tool", "Tool"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tool_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ide", "Ide"),
                            ("editor", "Editor"),
                            ("CI/CD", "Ci Cd"),
                            ("containerization", "Containerization"),
                            ("monitoring", "Monitoring"),
                            ("logging", "Logging"),
                            ("testing", "Testing"),
                            ("debugging", "Debugging"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("style", "Style"), ("ui", "Ui"), ("ux", "Ux"), ("logic", "Logic")],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LanguageSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("interested in learning", "Interested In Learning"),
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                            ("master", "Master"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "started_on",
                    models.DateField(
                        blank=True,
                        help_text="Date when this skill was started to be used or learned.",
                        null=True,
                    ),
                ),
                (
                    "last_used_on",
                    models.DateField(
                        blank=True, help_text="Date when this skill was last used.", null=True
                    ),
                ),
                (
                    "learned_with",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("courses", "Courses"),
                            ("practice", "Practice"),
                            ("exercises", "Exercises"),
                            ("projects", "Projects"),
                            ("books", "Books"),
                            ("tutorials", "Tutorials"),
                            ("documentations", "Documentations"),
                            ("mentors", "Mentors"),
                            ("ai bots", "Ai Bots"),
                            ("other", "Other"),
                        ],
                        help_text="Indicate with which tools or methods you learned this skill.",
                        max_length=88,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MobileSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("interested in learning", "Interested In Learning"),
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                            ("master", "Master"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "started_on",
                    models.DateField(
                        blank=True,
                        help_text="Date when this skill was started to be used or learned.",
                        null=True,
                    ),
                ),
                (
                    "last_used_on",
                    models.DateField(
                        blank=True, help_text="Date when this skill was last used.", null=True
                    ),
                ),
                (
                    "learned_with",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("courses", "Courses"),
                            ("practice", "Practice"),
                            ("exercises", "Exercises"),
                            ("projects", "Projects"),
                            ("books", "Books"),
                            ("tutorials", "Tutorials"),
                            ("documentations", "Documentations"),
                            ("mentors", "Mentors"),
                            ("ai bots", "Ai Bots"),
                            ("other", "Other"),
                        ],
                        help_text="Indicate with which tools or methods you learned this skill.",
                        max_length=88,
                        null=True,
                    ),
                ),
                (
                    "skill_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("language", "Language"),
                            ("framework", "Framework"),
                            ("library", "Library"),
                            ("tool", "Tool"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tool_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ide", "Ide"),
                            ("editor", "Editor"),
                            ("CI/CD", "Ci Cd"),
                            ("containerization", "Containerization"),
                            ("monitoring", "Monitoring"),
                            ("logging", "Logging"),
                            ("testing", "Testing"),
                            ("debugging", "Debugging"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("android", "Android"),
                            ("ios", "Ios"),
                            ("cross-platform", "Cross Platform"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
