# Generated by Django 5.1.2 on 2025-01-05 15:19

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backendskill",
            name="category",
        ),
        migrations.RemoveField(
            model_name="backendskill",
            name="skill_type",
        ),
        migrations.RemoveField(
            model_name="backendskill",
            name="tool_type",
        ),
        migrations.RemoveField(
            model_name="frontendskill",
            name="category",
        ),
        migrations.RemoveField(
            model_name="frontendskill",
            name="skill_type",
        ),
        migrations.RemoveField(
            model_name="frontendskill",
            name="tool_type",
        ),
        migrations.RemoveField(
            model_name="mobileskill",
            name="category",
        ),
        migrations.RemoveField(
            model_name="mobileskill",
            name="skill_type",
        ),
        migrations.RemoveField(
            model_name="mobileskill",
            name="tool_type",
        ),
        migrations.AddField(
            model_name="backendskill",
            name="categories",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("database", "Data Base"),
                    ("devops", "Devops"),
                    ("server", "Server"),
                    ("cloud", "Cloud"),
                    ("security", "Security"),
                ],
                max_length=37,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="backendskill",
            name="skill_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("language", "Language"),
                    ("framework", "Framework"),
                    ("library", "Library"),
                    ("tool", "Tool"),
                    ("run-time", "Run Time"),
                    ("bundler", "Bundler"),
                ],
                max_length=48,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="backendskill",
            name="tool_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("ide", "Ide"),
                    ("editor", "Editor"),
                    ("CI/CD", "Ci Cd"),
                    ("containerization", "Containerization"),
                    ("monitoring", "Monitoring"),
                    ("logging", "Logging"),
                    ("testing", "Testing"),
                    ("debugging", "Debugging"),
                ],
                max_length=70,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="frontendskill",
            name="categories",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("style", "Style"), ("ui", "Ui"), ("ux", "Ux"), ("logic", "Logic")],
                max_length=17,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="frontendskill",
            name="skill_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("language", "Language"),
                    ("framework", "Framework"),
                    ("library", "Library"),
                    ("tool", "Tool"),
                    ("run-time", "Run Time"),
                    ("bundler", "Bundler"),
                ],
                max_length=48,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="frontendskill",
            name="tool_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("ide", "Ide"),
                    ("editor", "Editor"),
                    ("CI/CD", "Ci Cd"),
                    ("containerization", "Containerization"),
                    ("monitoring", "Monitoring"),
                    ("logging", "Logging"),
                    ("testing", "Testing"),
                    ("debugging", "Debugging"),
                ],
                max_length=70,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mobileskill",
            name="categories",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("android", "Android"), ("ios", "Ios"), ("cross-platform", "Cross Platform")],
                max_length=26,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mobileskill",
            name="skill_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("language", "Language"),
                    ("framework", "Framework"),
                    ("library", "Library"),
                    ("tool", "Tool"),
                    ("run-time", "Run Time"),
                    ("bundler", "Bundler"),
                ],
                max_length=48,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mobileskill",
            name="tool_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("ide", "Ide"),
                    ("editor", "Editor"),
                    ("CI/CD", "Ci Cd"),
                    ("containerization", "Containerization"),
                    ("monitoring", "Monitoring"),
                    ("logging", "Logging"),
                    ("testing", "Testing"),
                    ("debugging", "Debugging"),
                ],
                max_length=70,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="backendskill",
            name="learned_with",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("courses", "Courses"),
                    ("practice", "Practice"),
                    ("exercises", "Exercises"),
                    ("projects", "Projects"),
                    ("books", "Books"),
                    ("tutorials", "Tutorials"),
                    ("documentations", "Documentations"),
                    ("mentors", "Mentors"),
                    ("ai bots", "Ai Bots"),
                ],
                help_text="Indicate with which tools or methods you learned this skill.",
                max_length=82,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="frontendskill",
            name="learned_with",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("courses", "Courses"),
                    ("practice", "Practice"),
                    ("exercises", "Exercises"),
                    ("projects", "Projects"),
                    ("books", "Books"),
                    ("tutorials", "Tutorials"),
                    ("documentations", "Documentations"),
                    ("mentors", "Mentors"),
                    ("ai bots", "Ai Bots"),
                ],
                help_text="Indicate with which tools or methods you learned this skill.",
                max_length=82,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="languageskill",
            name="learned_with",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("courses", "Courses"),
                    ("practice", "Practice"),
                    ("exercises", "Exercises"),
                    ("projects", "Projects"),
                    ("books", "Books"),
                    ("tutorials", "Tutorials"),
                    ("documentations", "Documentations"),
                    ("mentors", "Mentors"),
                    ("ai bots", "Ai Bots"),
                ],
                help_text="Indicate with which tools or methods you learned this skill.",
                max_length=82,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="languageskill",
            name="level",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("intermediate", "Intermediate"),
                    ("fluent", "Fluent"),
                    ("native", "Native"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mobileskill",
            name="learned_with",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("courses", "Courses"),
                    ("practice", "Practice"),
                    ("exercises", "Exercises"),
                    ("projects", "Projects"),
                    ("books", "Books"),
                    ("tutorials", "Tutorials"),
                    ("documentations", "Documentations"),
                    ("mentors", "Mentors"),
                    ("ai bots", "Ai Bots"),
                ],
                help_text="Indicate with which tools or methods you learned this skill.",
                max_length=82,
                null=True,
            ),
        ),
    ]
