# Generated by Django 5.1.2 on 2025-01-02 22:48

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asemployeeproject",
            name="goals",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("learning", "Learning"),
                    ("earn money", "Earn Money"),
                    ("showcasing", "Showcasing"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalproject",
            name="goals",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("learning", "Learning"),
                    ("earn money", "Earn Money"),
                    ("showcasing", "Showcasing"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamopensourceproject",
            name="goals",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("learning", "Learning"),
                    ("earn money", "Earn Money"),
                    ("showcasing", "Showcasing"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamprivateproject",
            name="goals",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("learning", "Learning"),
                    ("earn money", "Earn Money"),
                    ("showcasing", "Showcasing"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
