# Generated by Django 5.1.2 on 2025-01-03 14:48

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_asemployeeproject_goals_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asemployeeproject",
            name="categories",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("e-commerce", "E Commerce"),
                    ("logistics", "Logistics"),
                    ("community", "Community"),
                    ("game", "Game"),
                    ("portfolio", "Portfolio"),
                    ("blog", "Blog"),
                    ("other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asemployeeproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in progress", "In Progress"),
                    ("maintained", "Maintained"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                    ("paused", "Paused"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalproject",
            name="categories",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("e-commerce", "E Commerce"),
                    ("logistics", "Logistics"),
                    ("community", "Community"),
                    ("game", "Game"),
                    ("portfolio", "Portfolio"),
                    ("blog", "Blog"),
                    ("other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in progress", "In Progress"),
                    ("maintained", "Maintained"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                    ("paused", "Paused"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamopensourceproject",
            name="categories",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("e-commerce", "E Commerce"),
                    ("logistics", "Logistics"),
                    ("community", "Community"),
                    ("game", "Game"),
                    ("portfolio", "Portfolio"),
                    ("blog", "Blog"),
                    ("other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamopensourceproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in progress", "In Progress"),
                    ("maintained", "Maintained"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                    ("paused", "Paused"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamprivateproject",
            name="categories",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("e-commerce", "E Commerce"),
                    ("logistics", "Logistics"),
                    ("community", "Community"),
                    ("game", "Game"),
                    ("portfolio", "Portfolio"),
                    ("blog", "Blog"),
                    ("other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamprivateproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in progress", "In Progress"),
                    ("maintained", "Maintained"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                    ("paused", "Paused"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
