# Generated by Django 5.1.2 on 2025-01-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_customercompany_company_type_and_more"),
        ("projects", "0003_alter_asemployeeproject_categories_and_more"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asemployeeproject",
            name="backend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="as_employee_projects", to="skills.backendskill"
            ),
        ),
        migrations.AddField(
            model_name="asemployeeproject",
            name="frontend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="as_employee_projects", to="skills.frontendskill"
            ),
        ),
        migrations.AddField(
            model_name="asemployeeproject",
            name="mobile_stack",
            field=models.ManyToManyField(
                blank=True, related_name="as_employee_projects", to="skills.mobileskill"
            ),
        ),
        migrations.AddField(
            model_name="personalproject",
            name="backend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="personal_projects", to="skills.backendskill"
            ),
        ),
        migrations.AddField(
            model_name="personalproject",
            name="frontend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="personal_projects", to="skills.frontendskill"
            ),
        ),
        migrations.AddField(
            model_name="personalproject",
            name="mobile_stack",
            field=models.ManyToManyField(
                blank=True, related_name="personal_projects", to="skills.mobileskill"
            ),
        ),
        migrations.AddField(
            model_name="teamopensourceproject",
            name="backend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="team_open_source_projects", to="skills.backendskill"
            ),
        ),
        migrations.AddField(
            model_name="teamopensourceproject",
            name="frontend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="team_open_source_projects", to="skills.frontendskill"
            ),
        ),
        migrations.AddField(
            model_name="teamopensourceproject",
            name="mobile_stack",
            field=models.ManyToManyField(
                blank=True, related_name="team_open_source_projects", to="skills.mobileskill"
            ),
        ),
        migrations.AddField(
            model_name="teamprivateproject",
            name="backend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="team_private_projects", to="skills.backendskill"
            ),
        ),
        migrations.AddField(
            model_name="teamprivateproject",
            name="frontend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="team_private_projects", to="skills.frontendskill"
            ),
        ),
        migrations.AddField(
            model_name="teamprivateproject",
            name="mobile_stack",
            field=models.ManyToManyField(
                blank=True, related_name="team_private_projects", to="skills.mobileskill"
            ),
        ),
        migrations.AlterField(
            model_name="asemployeeproject",
            name="customer_companies",
            field=models.ManyToManyField(
                related_name="as_employee_projects", to="companies.customercompany"
            ),
        ),
    ]
