# Generated by Django 5.1.2 on 2025-01-05 14:30

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_customercompany_backend_skills_and_more"),
        ("projects", "0004_asemployeeproject_backend_stack_and_more"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asemployeeproject",
            name="contribution_role",
            field=models.CharField(
                choices=[
                    ("Frontend Developer", "Frontend Developer"),
                    ("Full Stack Developer", "Full Stack Developer"),
                    ("Backend Developer", "Backend Developer"),
                    ("Android Developer", "Android Developer"),
                    ("iOS Developer", "Ios Developer"),
                    ("Cross-Platform Developer", "Cross Platform Developer"),
                    ("DevOps", "Devops"),
                ],
                default="Full Stack Developer",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalproject",
            name="contribution_role",
            field=models.CharField(
                choices=[
                    ("Frontend Developer", "Frontend Developer"),
                    ("Full Stack Developer", "Full Stack Developer"),
                    ("Backend Developer", "Backend Developer"),
                    ("Android Developer", "Android Developer"),
                    ("iOS Developer", "Ios Developer"),
                    ("Cross-Platform Developer", "Cross Platform Developer"),
                    ("DevOps", "Devops"),
                ],
                default="Full Stack Developer",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teamopensourceproject",
            name="contribution_role",
            field=models.CharField(
                choices=[
                    ("Frontend Developer", "Frontend Developer"),
                    ("Full Stack Developer", "Full Stack Developer"),
                    ("Backend Developer", "Backend Developer"),
                    ("Android Developer", "Android Developer"),
                    ("iOS Developer", "Ios Developer"),
                    ("Cross-Platform Developer", "Cross Platform Developer"),
                    ("DevOps", "Devops"),
                ],
                default="Full Stack Developer",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teamprivateproject",
            name="contribution_role",
            field=models.CharField(
                choices=[
                    ("Frontend Developer", "Frontend Developer"),
                    ("Full Stack Developer", "Full Stack Developer"),
                    ("Backend Developer", "Backend Developer"),
                    ("Android Developer", "Android Developer"),
                    ("iOS Developer", "Ios Developer"),
                    ("Cross-Platform Developer", "Cross Platform Developer"),
                    ("DevOps", "Devops"),
                ],
                default="Full Stack Developer",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asemployeeproject",
            name="backend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="as_employee_backend_projects", to="skills.backendskill"
            ),
        ),
        migrations.AlterField(
            model_name="asemployeeproject",
            name="categories",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("e-commerce", "E Commerce"),
                    ("logistics", "Logistics"),
                    ("community", "Community"),
                    ("game", "Game"),
                    ("portfolio", "Portfolio"),
                    ("blog", "Blog"),
                    ("other", "Other"),
                ],
                max_length=56,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asemployeeproject",
            name="customer_companies",
            field=models.ManyToManyField(
                blank=True, related_name="as_employee_projects", to="companies.customercompany"
            ),
        ),
        migrations.AlterField(
            model_name="asemployeeproject",
            name="employed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="as_employee_projects",
                to="companies.employercompany",
            ),
        ),
        migrations.AlterField(
            model_name="asemployeeproject",
            name="frontend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="as_employee_frontend_projects", to="skills.frontendskill"
            ),
        ),
        migrations.AlterField(
            model_name="asemployeeproject",
            name="goals",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("learning", "Learning"),
                    ("earn money", "Earn Money"),
                    ("showcasing", "Showcasing"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asemployeeproject",
            name="mobile_stack",
            field=models.ManyToManyField(
                blank=True, related_name="as_employee_mobile_projects", to="skills.mobileskill"
            ),
        ),
        migrations.AlterField(
            model_name="asemployeeproject",
            name="runs_on",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("web", "Web"), ("desktop", "Desktop"), ("ios", "Ios"), ("android", "Android")],
                max_length=23,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asemployeeproject",
            name="size",
            field=models.CharField(
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("big", "Big"),
                    ("very big", "Very Big"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asemployeeproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in progress", "In Progress"),
                    ("maintained", "Maintained"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                    ("paused", "Paused"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalproject",
            name="backend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="personal_backend_projects", to="skills.backendskill"
            ),
        ),
        migrations.AlterField(
            model_name="personalproject",
            name="categories",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("e-commerce", "E Commerce"),
                    ("logistics", "Logistics"),
                    ("community", "Community"),
                    ("game", "Game"),
                    ("portfolio", "Portfolio"),
                    ("blog", "Blog"),
                    ("other", "Other"),
                ],
                max_length=56,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalproject",
            name="frontend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="personal_frontend_projects", to="skills.frontendskill"
            ),
        ),
        migrations.AlterField(
            model_name="personalproject",
            name="goals",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("learning", "Learning"),
                    ("earn money", "Earn Money"),
                    ("showcasing", "Showcasing"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalproject",
            name="mobile_stack",
            field=models.ManyToManyField(
                blank=True, related_name="personal_mobile_projects", to="skills.mobileskill"
            ),
        ),
        migrations.AlterField(
            model_name="personalproject",
            name="runs_on",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("web", "Web"), ("desktop", "Desktop"), ("ios", "Ios"), ("android", "Android")],
                max_length=23,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalproject",
            name="size",
            field=models.CharField(
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("big", "Big"),
                    ("very big", "Very Big"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in progress", "In Progress"),
                    ("maintained", "Maintained"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                    ("paused", "Paused"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamopensourceproject",
            name="backend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="team_open_source_backend_projects", to="skills.backendskill"
            ),
        ),
        migrations.AlterField(
            model_name="teamopensourceproject",
            name="categories",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("e-commerce", "E Commerce"),
                    ("logistics", "Logistics"),
                    ("community", "Community"),
                    ("game", "Game"),
                    ("portfolio", "Portfolio"),
                    ("blog", "Blog"),
                    ("other", "Other"),
                ],
                max_length=56,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamopensourceproject",
            name="frontend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="team_open_source_frontend_projects", to="skills.frontendskill"
            ),
        ),
        migrations.AlterField(
            model_name="teamopensourceproject",
            name="goals",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("learning", "Learning"),
                    ("earn money", "Earn Money"),
                    ("showcasing", "Showcasing"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamopensourceproject",
            name="mobile_stack",
            field=models.ManyToManyField(
                blank=True, related_name="team_open_source_mobile_projects", to="skills.mobileskill"
            ),
        ),
        migrations.AlterField(
            model_name="teamopensourceproject",
            name="runs_on",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("web", "Web"), ("desktop", "Desktop"), ("ios", "Ios"), ("android", "Android")],
                max_length=23,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamopensourceproject",
            name="size",
            field=models.CharField(
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("big", "Big"),
                    ("very big", "Very Big"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamopensourceproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in progress", "In Progress"),
                    ("maintained", "Maintained"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                    ("paused", "Paused"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamprivateproject",
            name="backend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="team_private_backend_projects", to="skills.backendskill"
            ),
        ),
        migrations.AlterField(
            model_name="teamprivateproject",
            name="categories",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("e-commerce", "E Commerce"),
                    ("logistics", "Logistics"),
                    ("community", "Community"),
                    ("game", "Game"),
                    ("portfolio", "Portfolio"),
                    ("blog", "Blog"),
                    ("other", "Other"),
                ],
                max_length=56,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamprivateproject",
            name="frontend_stack",
            field=models.ManyToManyField(
                blank=True, related_name="team_private_frontend_projects", to="skills.frontendskill"
            ),
        ),
        migrations.AlterField(
            model_name="teamprivateproject",
            name="goals",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("learning", "Learning"),
                    ("earn money", "Earn Money"),
                    ("showcasing", "Showcasing"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamprivateproject",
            name="mobile_stack",
            field=models.ManyToManyField(
                blank=True, related_name="team_private_mobile_projects", to="skills.mobileskill"
            ),
        ),
        migrations.AlterField(
            model_name="teamprivateproject",
            name="runs_on",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("web", "Web"), ("desktop", "Desktop"), ("ios", "Ios"), ("android", "Android")],
                max_length=23,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamprivateproject",
            name="size",
            field=models.CharField(
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("big", "Big"),
                    ("very big", "Very Big"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamprivateproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in progress", "In Progress"),
                    ("maintained", "Maintained"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                    ("paused", "Paused"),
                ],
                null=True,
            ),
        ),
    ]
